readme:
- '**/README.md'

actions:
- .github/workflows/**/*
- .github/labeler.yml

# Playbook

playbook:
- src/**/*

appx:
- src/Configuration/void/appx.yml

components:
- src/Configuration/void/components.yml
- src/Configuration/void/packages.yml

config:
- src/Configuration/void/config.yml

services:
- src/Configuration/void/services.yml

tweaks:
- src/Configuration/tweaks.yml
- src/Configuration/tweaks/**/*

desktop folder:
- src/Executables/VoidDesktop/**/*
