---
title: Applies Void's Network Settings
description: Applies Void's optimised network settings
actions:
  - !cmd:
    command: '"VoidDesktop\9. Troubleshooting\Network\Reset Network to Void Default.cmd" /silent'
    exeDir: true
    wait: true
    runas: currentUserElevated
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile'
    value: 'NetworkThrottlingIndex'
    data: '4294967295' # 0xFFFFFFFF
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile'
    value: 'SystemResponsiveness'
    data: '0'
    type: REG_DWORD

# VOID-OS-HASH-EVASION-a27e9ff1-5fa2-4af6-8275-65aaa1664bdc
