---
title: Applies Void's Network Settings
description: Applies Void's optimised network settings
actions:
  - !cmd:
    command: '"VoidDesktop\9. Troubleshooting\Network\Reset Network to Void Default.cmd" /silent'
    exeDir: true
    wait: true
    runas: currentUserElevated
